### ISSUE TITLE
Default Directive

### ISSUE THREAD

**Issue by Goldstein777** [Ketcap/Talk-to-AI#14]
**Is your feature request related to a problem? Please describe.**
Not a big issue, just tiny.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/114928555/229307717-67736bc8-821f-4d9f-9cd5-6f2c000d4ba2.png">

**Describe the solution you'd like**
Have a Default "You are a helpful assistant." directive.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Ketcap** [comment]
👍
