### ISSUE TITLE
ElevenLabs Stability + Clarity Voice Settings

### ISSUE THREAD

**Issue by Goldstein777** [Ketcap/Talk-to-AI#5]
After having more conversation, I realized being able to adjust the stability and clarity voice settings from ElevenLabs would make the chats even more immersive. I figure the current settings are the default ones? Often, especially with emotions, stability adjustment can change the whole output and depending who you talk to this makes total sense so:

- Stability/Clarity voice Settings adjustment when creating a new chat

**Comment by Ketcap** [comment]
Just to get a feedback from you,
We have a voice creation if voice is not selected for room, how would you expect that to be solved from user perspective. Because that one is just a dropdown.
Shall we have some test voice button as well when those params are handled ?

**Comment by Goldstein777** [comment]
That sounds good actually, a test voice button if user does not select a voice.

I particular, I was talking about these sliders:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/114928555/227468480-c31bc1ab-45ba-49e3-9a80-28da9652afd4.png">

So if user chooses a voice from dropdown, they can also change these parameters before creating the chat room to their liking. I tested the outputs from TalkToAi and put them into ElevenLabs with lower stability and it sounds more like a conversation from in my opinion, instead of the usual default settings.

**Comment by Ketcap** [comment]
Thanks for the feedback i'll try to add them today/ tomorrow, or feel free to create a pr for that we should have a readme now :)

**Comment by Ketcap** [comment]
@Goldstein777 this has been added to the room creation let me know if you have more feedback. Thanks alot <3
