### ISSUE TITLE
Chatbox needs to be clicked each time you want to type a message

### ISSUE THREAD

**Issue by Goldstein777** [Ketcap/Talk-to-AI#8]
**Describe the bug**
Once you've hit "enter" and send a message, you have to click the chatbox again to write.

**Expected behavior**
After hitting "enter" and sending a message, the chatbox should stay active so you can instantly type another message without clicking the box again.

**Screenshots**
<img width="653" alt="image" src="https://user-images.githubusercontent.com/114928555/227907586-15a4a44b-df2c-45ff-8bba-5574544b5d5e.png">

**Desktop (please complete the following information):**
 - OS: [Win 1]
 - Browser [Edge]

**Comment by Ketcap** [comment]
Should be done with the marked commit
